[build]
  command = "bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_YARN = "true"
  NEXT_TELEMETRY_DISABLED = "1"

[images]
  remote_images = ["https://ext.same-assets.com/*"]
